# Site settings
title: Password Policy Wall Of Shame
description: A list of websites that have a bad password policy.
baseurl: /password-policy-wall-of-shame
url: http://publicarray.github.io/password-policy-wall-of-shame
repository: publicarray/password-policy-wall-of-shame

# Custom settings
permalink: :title
paginate: 5
paginate_path: "/:num/"
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "posts"

webrick:
  headers:
    Content-Security-Policy-Report-Only: "default-src 'none'; script-src 'self'; style-src 'self' fonts.googleapis.com; img-src *; font-src 'self' data: fonts.googleapis.com; form-action 'self'; block-all-mixed-content; reflected-xss block; report-uri https://publicarray.report-uri.io/r/default/csp/reportOnly;"
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false

sass:
    style: :compressed

gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - package.json
    - semantic.json
    - node_modules
    - semantic/src
    - semantic/tasks
    - semantic/gulpfile.js
